addSbtPlugin("org.scoverage"      % "sbt-scoverage"         % "1.6.0")
addSbtPlugin("net.virtual-void"   % "sbt-dependency-graph"  % "0.9.2")
addSbtPlugin("com.github.gseitz"  % "sbt-release"           % "1.0.11")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"          % "3.6")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"               % "1.1.2")